export const SET_NUMBER = "SET_NUMBER";
export const CLEAR_NUMBER = "CLEAR_NUMBER";
export const DELETE_LAST_DIGIT = "DELETE_LAST_DIGIT";
export const SET_OPERATION = "SET_OPERATION"; 
export const CALCULATE = "CALCULATE"; 